/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ativaval1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cadua
 */
public class IntGraf2D extends javax.swing.JFrame {
    ArrayList<Triangulo> triangs = new ArrayList();
    ArrayList<Retangulo> retangs = new ArrayList();
    ArrayList<Circulo> circs = new ArrayList();
    ArrayList<Trapezoide> traps = new ArrayList();
    /**
     * Creates new form IntGraf2D
     */
    public IntGraf2D() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Triangulo = new javax.swing.JButton();
        Circulo = new javax.swing.JButton();
        Retangulo = new javax.swing.JButton();
        Trapezio = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        TriNome = new javax.swing.JTextField();
        TriBase = new javax.swing.JTextField();
        TriAltura = new javax.swing.JTextField();
        CirNome = new javax.swing.JTextField();
        RetAltura = new javax.swing.JTextField();
        RetBase = new javax.swing.JTextField();
        RetNome = new javax.swing.JTextField();
        CirRaio = new javax.swing.JTextField();
        TrapAltura = new javax.swing.JTextField();
        TrapNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TrapB1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TrapB2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CircPerim = new javax.swing.JButton();
        TriPerim = new javax.swing.JButton();
        TriArea = new javax.swing.JButton();
        RetArea = new javax.swing.JButton();
        CircArea = new javax.swing.JButton();
        TrapArea = new javax.swing.JButton();
        RetPerim = new javax.swing.JButton();
        TrapPerim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formas 2D");
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.gray);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        Triangulo.setText("+Triangulo");
        Triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrianguloActionPerformed(evt);
            }
        });

        Circulo.setText("+Circulo");
        Circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CirculoActionPerformed(evt);
            }
        });

        Retangulo.setText("+Retangulo");
        Retangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetanguloActionPerformed(evt);
            }
        });

        Trapezio.setText("+Trapezio");
        Trapezio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrapezioActionPerformed(evt);
            }
        });

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Inserir formas 2D");

        TriNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Nome:");

        jLabel5.setText("Nome:");

        jLabel6.setText("Base:");

        jLabel7.setText("Altura:");

        jLabel8.setText("Raio:");

        jLabel9.setText("Base 1:");

        jLabel10.setText("Base 2:");

        jLabel11.setText("Altura:");

        jLabel13.setText("Base:");

        jLabel14.setText("Altura:");

        CircPerim.setText("Perímetro");
        CircPerim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircPerimActionPerformed(evt);
            }
        });

        TriPerim.setText("Perímetro");
        TriPerim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriPerimActionPerformed(evt);
            }
        });

        TriArea.setText("Area");
        TriArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriAreaActionPerformed(evt);
            }
        });

        RetArea.setText("Area");
        RetArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetAreaActionPerformed(evt);
            }
        });

        CircArea.setText("Area");
        CircArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircAreaActionPerformed(evt);
            }
        });

        TrapArea.setText("Area");
        TrapArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrapAreaActionPerformed(evt);
            }
        });

        RetPerim.setText("Perímetro");
        RetPerim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetPerimActionPerformed(evt);
            }
        });

        TrapPerim.setText("Perímetro");
        TrapPerim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrapPerimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TriArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TriAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TriNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TriBase, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TriPerim))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(6, 6, 6)
                                .addComponent(RetAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(RetArea)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Retangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RetBase, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RetNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RetPerim)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TrapAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(TrapArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrapB1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TrapNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Trapezio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TrapB2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(CircArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CirNome)
                            .addComponent(CirRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CircPerim)
                    .addComponent(TrapPerim, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TriPerim)
                            .addComponent(TriArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TriNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TriBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TriAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Retangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RetArea)
                            .addComponent(RetPerim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RetNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RetBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RetAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CircArea)
                            .addComponent(CircPerim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CirRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Trapezio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TrapArea)
                            .addComponent(TrapPerim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(TrapNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TrapB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TrapB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TrapAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TriNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriNomeActionPerformed
        
    }//GEN-LAST:event_TriNomeActionPerformed

    private void TrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrianguloActionPerformed
        String trinome = TriNome.getText();
        String tribase = TriBase.getText();
        String trialtura = TriAltura.getText();
        Triangulo tri1 = new Triangulo(trinome, Double.parseDouble(tribase), Double.parseDouble(trialtura));
        triangs.add(tri1);
        JOptionPane.showMessageDialog(null, "Triangulo adicionado");
        TriNome.setText("");
        TriBase.setText("");
        TriAltura.setText("");
    }//GEN-LAST:event_TrianguloActionPerformed

    private void TrapezioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrapezioActionPerformed
        String trapnome = TrapNome.getText();
        String trapb1 = TrapB1.getText();
        String trapb2 = TrapB2.getText();
        String trapaltura = TrapAltura.getText();
        Trapezoide trap1 = new Trapezoide(trapnome, Double.parseDouble(trapb1), Double.parseDouble(trapb2), Double.parseDouble(trapaltura));
        traps.add(trap1);
        JOptionPane.showMessageDialog(null, "Trapezio adicionado");
        TrapNome.setText("");
        TrapB1.setText("");
        TrapB2.setText("");
        TrapAltura.setText("");
    }//GEN-LAST:event_TrapezioActionPerformed

    private void RetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetanguloActionPerformed
        String retnome = RetNome.getText();
        String retbase = RetBase.getText();
        String retaltura = RetAltura.getText();
        Retangulo ret1 = new Retangulo(retnome, Double.parseDouble(retbase), Double.parseDouble(retaltura));
        retangs.add(ret1);
        JOptionPane.showMessageDialog(null, "Retangulo adicionado");
        RetNome.setText("");
        RetBase.setText("");
        RetAltura.setText("");
    }//GEN-LAST:event_RetanguloActionPerformed

    private void CirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CirculoActionPerformed
        String cirnome = CirNome.getText();
        String cirraio = CirRaio.getText();
        Circulo circ1 = new Circulo(cirnome, Double.parseDouble(cirraio));
        circs.add(circ1);
        JOptionPane.showMessageDialog(null, "Circulo adicionado");
        CirNome.setText("");
        CirRaio.setText("");
    }//GEN-LAST:event_CirculoActionPerformed

    private void TriAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriAreaActionPerformed
        for(int i = 0; i < triangs.size();i++){
        String msg = "Area do "+triangs.get(i).nome+": "+triangs.get(i).calcularArea();
        JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_TriAreaActionPerformed

    private void TriPerimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriPerimActionPerformed
        for(int i = 0; i < triangs.size();i++){
        String msg = "Perimetro do "+triangs.get(i).nome+": "+triangs.get(i).calcularPerimetro()+"\n";
        JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_TriPerimActionPerformed

    private void CircAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircAreaActionPerformed
        for(int i = 0; i < circs.size();i++){
        String msg = "Area do "+circs.get(i).nome+": "+circs.get(i).calcularArea();
        JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_CircAreaActionPerformed

    private void CircPerimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircPerimActionPerformed
        for(int i = 0; i < circs.size();i++){
        String msg = "Perimetro do "+circs.get(i).nome+": "+circs.get(i).calcularPerimetro()+"\n";
        JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_CircPerimActionPerformed

    private void RetAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetAreaActionPerformed
        for(int i = 0; i < retangs.size();i++){
        String msg = "Area do "+retangs.get(i).nome+": "+retangs.get(i).calcularArea();
        JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_RetAreaActionPerformed

    private void RetPerimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetPerimActionPerformed
        for(int i = 0; i < retangs.size();i++){
        String msg = "Perimetro do "+retangs.get(i).nome+": "+retangs.get(i).calcularPerimetro()+"\n";
        JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_RetPerimActionPerformed

    private void TrapAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrapAreaActionPerformed
        for(int i = 0; i < traps.size();i++){
        String msg = "Area do "+traps.get(i).nome+": "+traps.get(i).calcularArea();
        JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_TrapAreaActionPerformed

    private void TrapPerimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrapPerimActionPerformed
        for(int i = 0; i < traps.size();i++){
        String msg = "Perimetro do "+traps.get(i).nome+": "+traps.get(i).calcularPerimetro()+"\n";
        JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_TrapPerimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntGraf2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntGraf2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntGraf2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntGraf2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntGraf2D().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CirNome;
    private javax.swing.JTextField CirRaio;
    private javax.swing.JButton CircArea;
    private javax.swing.JButton CircPerim;
    private javax.swing.JButton Circulo;
    private javax.swing.JTextField RetAltura;
    private javax.swing.JButton RetArea;
    private javax.swing.JTextField RetBase;
    private javax.swing.JTextField RetNome;
    private javax.swing.JButton RetPerim;
    private javax.swing.JButton Retangulo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField TrapAltura;
    private javax.swing.JButton TrapArea;
    private javax.swing.JTextField TrapB1;
    private javax.swing.JTextField TrapB2;
    private javax.swing.JTextField TrapNome;
    private javax.swing.JButton TrapPerim;
    private javax.swing.JButton Trapezio;
    private javax.swing.JTextField TriAltura;
    private javax.swing.JButton TriArea;
    private javax.swing.JTextField TriBase;
    private javax.swing.JTextField TriNome;
    private javax.swing.JButton TriPerim;
    private javax.swing.JButton Triangulo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
